- kind: Message
  name: ReplacePrimaryPaymentMethodRl
  fields:
    - name: accountId
      type: string
      index: 1
- kind: Message
  name: VerifyEmailRl
  fields:
    - name: tokenId
      type: string
      index: 1
- kind: Message
  name: ResetPasswordRl
  fields:
    - name: tokenId
      type: string
      index: 1
- kind: Message
  name: AppRl
  fields:
    - name: main
      type: MainAppRl
      import: ./main/app
      index: 1
    - name: replacePrimaryPaymentMethod
      type: ReplacePrimaryPaymentMethodRl
      index: 2
    - name: verifyEmail
      type: VerifyEmailRl
      index: 3
    - name: resetPassword
      type: ResetPasswordRl
      index: 4
    - name: marketing
      type: Empty
      import: ./empty
      index: 5
