- kind: Message
  name: ChooseAccountPage
  fields:
    - name: accountId
      type: string
      index: 1
- kind: Message
  name: MainAppRl
  fields:
    - name: chooseAccount
      type: ChooseAccountPage
      index: 1
    - name: account
      type: AccountPageRl
      import: ./main/account/page
      index: 2
    - name: consumer
      type: ConsumerPageRl
      import: ./main/consumer/page
      index: 3
    - name: publisher
      type: PublisherPageRl
      import: ./main/publisher/page
      index: 4
